# Generated by Django 3.1.7 on 2021-02-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructors',
            new_name='Instructor',
        ),
    ]
